//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ME630Demo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ME630DEMO_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_DIALOG_TITLE                129
#define IDC_BOARD_COMBO                 1000
#define IDC_GET_RELAY_BIT_7             1001
#define IDC_GET_RELAY_BIT_6             1003
#define IDC_GET_RELAY_BIT_5             1004
#define IDC_GET_RELAY_BIT_4             1005
#define IDC_GET_RELAY_BIT_15            1006
#define IDC_GET_RELAY_BIT_14            1007
#define IDC_GET_RELAY_BIT_13            1008
#define IDC_GET_RELAY_BIT_12            1009
#define IDC_GET_TTL_BIT_7               1010
#define IDC_GET_TTL_BIT_6               1011
#define IDC_GET_TTL_BIT_5               1012
#define IDC_GET_TTL_BIT_4               1013
#define IDC_DIO_GET_BYTE_7              1014
#define IDC_VENDOR_ID                   1015
#define IDC_DEVICE_ID                   1016
#define IDC_SYSTEM_SLOT_NUMBER          1017
#define IDC_GET_RELAY_BIT_3             1018
#define IDC_GET_RELAY_BIT_2             1019
#define IDC_GET_RELAY_BIT_1             1020
#define IDC_GET_RELAY_BIT_0             1021
#define IDC_GET_RELAY_BIT_11            1022
#define IDC_GET_RELAY_BIT_10            1023
#define IDC_GET_RELAY_BIT_9             1024
#define IDC_GET_RELAY_BIT_8             1025
#define IDC_GET_TTL_BIT_3               1026
#define IDC_PORT_BASE                   1027
#define IDC_PORT_COUNT                  1028
#define IDC_INTERRUPT_CHANNEL           1029
#define IDC_PLX_PORT_BASE               1030
#define IDC_PLX_PORT_COUNT              1031
#define IDC_SERIAL_NUMBER               1032
#define IDC_BUS_NUMBER                  1033
#define IDC_HW_REVISION                 1034
#define IDC_IRQ_COUNT                   1035
#define IDC_VERSION                     1036
#define IDC_GET_TTL_BIT_2               1037
#define IDC_GET_TTL_BIT_1               1038
#define IDC_GET_TTL_BIT_0               1039
#define IDC_DIO_GET_BYTE_3              1040
#define IDC_DIO_GET_BYTE_6              1041
#define IDC_DIO_GET_BYTE_5              1042
#define IDC_SET_RELAY_BIT_7             1043
#define IDC_CHECK11                     1044
#define IDC_SET_RELAY_BIT_6             1045
#define IDC_SET_RELAY_BIT_5             1046
#define IDC_SET_RELAY_BIT_4             1047
#define IDC_SET_RELAY_BIT_15            1048
#define IDC_SET_RELAY_BIT_14            1049
#define IDC_SET_RELAY_BIT_13            1050
#define IDC_SET_RELAY_BIT_12            1051
#define IDC_SET_RELAY_BIT_3             1052
#define IDC_SET_RELAY_BIT_2             1053
#define IDC_SET_RELAY_BIT_1             1054
#define IDC_SET_RELAY_BIT_0             1055
#define IDC_SET_RELAY_BIT_11            1056
#define IDC_SET_RELAY_BIT_10            1057
#define IDC_SET_RELAY_BIT_9             1058
#define IDC_SET_RELAY_BIT_8             1059
#define IDC_DIO_GET_BYTE_4              1060
#define IDC_DIO_GET_BYTE_2              1061
#define IDC_DIO_GET_BYTE_1              1062
#define IDC_DIO_GET_BYTE_0              1063
#define IDC_DIO_SET_BYTE_3              1064
#define IDC_DIO_SET_BYTE_7              1065
#define IDC_GET_OPTO_BIT_3              1066
#define IDC_GET_OPTO_BIT_7              1067
#define IDC_GET_OPTO_BIT_6              1068
#define IDC_GET_OPTO_BIT_5              1069
#define IDC_GET_OPTO_BIT_4              1070
#define IDC_GET_OPTO_BIT_2              1071
#define IDC_GET_OPTO_BIT_1              1072
#define IDC_GET_OPTO_BIT_0              1073
#define IDC_DIO_SET_BYTE_6              1074
#define IDC_DIO_SET_BYTE_5              1075
#define IDC_DIO_SET_BYTE_4              1076
#define IDC_DIO_SET_BYTE_2              1077
#define IDC_DIO_SET_BYTE_1              1078
#define IDC_DIO_SET_BYTE_0              1079
#define IDC_CHECK4                      1082
#define IDC_RADIO_IRQ1_DISABLE          1083
#define IDC_RADIO_IRQ1_ENABLE           1084
#define IDC_IRQ1_COUNT                  1085
#define IDC_RADIO_IRQ2_DISABLE          1086
#define IDC_RADIO_IRQ2_ENABLE           1087
#define IDC_IRQ2_COUNT                  1088
#define IDC_BUTTON_DIO_RESET_ALL        1089
#define IDC_RADIO_DIO_CONFIG_PORT_C     1090
#define IDC_RADIO_DIO_CONFIG_PORT_D     1091
#define IDC_RADIO_CONFIG_INPUT          1092
#define IDC_RADIO_DIO_CONFIG_INPUT      1092
#define IDC_RADIO_CONFIG_OUTPUT         1093
#define IDC_RADIO_DIO_CONFIG_OUTPUT     1093
#define IDC_BUTTON_DIO_CONFIG           1094
#define IDC_BUTTON_GET_RELAY_WORD       1095
#define IDC_BUTTON_SET_RELAY_WORD       1096
#define IDC_RADIO_DIO_SET_BYTE_PORT_C   1097
#define IDC_BUTTON_GET_TTL_BYTE         1098
#define IDC_BUTTON_GET_OPTO_BYTE        1099
#define IDC_BUTTON_DIO_GET_BYTE         1100
#define IDC_BUTTON_DIO_SET_BYTE         1101
#define IDC_RADIO_DIO_SET_BYTE_PORT_D   1102
#define IDC_RADIO_DIO_GET_BYTE_PORT_C   1103
#define IDC_RADIO_DIO_GET_BYTE_PORT_D   1104
#define IDC_RADIO_DIO_GET_BIT_PORT_C    1105
#define IDC_COMBO_GET_RELAY_BIT_NUMBER  1106
#define IDC_BUTTON_GET_RELAY_BIT        1107
#define IDC_CHECK_GET_RELAY_BIT_VALUE   1108
#define IDC_COMBO_SET_RELAY_BIT_NUMBER  1109
#define IDC_BUTTON_SET_RELAY_BIT        1110
#define IDC_CHECK_SET_RELAY_BIT_VALUE   1111
#define IDC_COMBO_GET_TTL_BIT_NUMBER    1112
#define IDC_BUTTON_GET_TTL_BIT          1113
#define IDC_CHECK_GET_TTL_BIT_VALUE     1114
#define IDC_COMBO_GET_OPTO_BIT_NUMBER   1115
#define IDC_BUTTON_GET_OPTO_BIT         1116
#define IDC_CHECK_GET_OPTO_BIT_VALUE    1117
#define IDC_COMBO_DIO_GET_BIT           1118
#define IDC_BUTTON_DIO_GET_BIT          1119
#define IDC_CHECK_DIO_GET_BIT           1120
#define IDC_COMBO_DIO_SET_BIT           1121
#define IDC_BUTTON_DIO_SET_BIT          1122
#define IDC_CHECK_DIO_SET_BIT           1123
#define IDC_RADIO_DIO_GET_BIT_PORT_D    1124
#define IDC_RADIO_DIO_SET_BIT_PORT_C    1125
#define IDC_RADIO_DIO_GET_BIT_PORT_D2   1126
#define IDC_RADIO_DIO_SET_BIT_PORT_D    1126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
